travis:
  secure:
    BINSTAR_TOKEN: pu0U3wwbbOmigDAOlZdNJ05QsfN6kZ3WOL2wUuhRseA0DQ5M5Gb2kdsFsWKGkkO+IFGuNO9s4lp3lg+tzpjK4RFcq50THfRqWj3kHoEdROs4cxIJwxqSrD9ztCUvJSCCam9JKOpAsDMxx71P07kvtqMNWnH2wohwPNfOJA2LCua5Fka01YP4zGE04WffgdaqN+567B/wuii+Q628wjZvnahrnpvp2/jWcGe8WyN2DBofoos/WqZGxJbdluOwhXa0hJcteTw0Psl8N8JSxHJ7pYMHQIcWm2YDO4GNff0QySiMPEj4L/lk+mFLtt2a+FfQ1xdtpVcsjkCKoDU9nUJLMeeqQ6jc07eQg0IUdrmOGYtIog/3UzrlfGLX//kQS3f1+Lfeuy+ATPpB+s2Uj00hqcfEvlRiXITEpnkXfcu755XT3ghIr4c6TLXX6SvAI2kttPcawhw76bSQx/sbP1ulBv6/P++N6hIsz/xXuGJ8goZPDmfCBSuBJpUulysLBJ45MDRR6fDnAymNGs7LEiSODWKjuUA48s0bA+s0NFtRk0b5fVoQW3DhUpYHWw5MGlcUPGPMJjQ44aNXapbXPCPgPNKb1xTVPz7BrWxdS1mN+uQGb82fP4ekwGWUxlgIvsbH2hYL0MczCNKvZAo2V0/kS34O7rh81rRRu7/FDBPmGOM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
